### ISSUE TITLE
Create Blocks page

### ISSUE THREAD

**Issue by dylancm4** [dfinityexplorer/dfinityexplorer#12]
(Note that this description is identical to that of "Create Transactions page".)

The Blocks and Transactions tabs in the App Bar currently aren't wired to anything, but when you click on one of these you should be brought to a Blocks or Transactions page. These pages would contain tables similar to Recent Blocks and Recent Transactions, but since the tables are larger, they could accommodate more columns and rows.

See these pages on etherscan.io:
https://etherscan.io/blocks
https://etherscan.io/txs

Also look at how other block explorers implement these pages:
https://github.com/dfinityexplorer/dfinityexplorer/wiki/Other-Block-Explorers

The FadeTable component could be used as a base class, just as it's used for Recent Blocks (BlocksTable) and Recent Transactions (TransactionsTable). It probably makes sense to rename BlocksTable and TransactionsTable if these components will only be used on the front page, perhaps using the word "compact" to distinguish them.

It's not necessary to derive from FadeTable or even use a table at all. If you have creative ideas about how to present the information in the Blocks and Transactions pages, bring those ideas up for discussion in the Telegram group!

A word of warning. If we use react-router-dom for routing between pages, there is an issue to be aware of regarding how create-react-app works with GitHub pages (which is currently hosting dfinityexplorer.org). Read about this under "Notes on client-side routing" here:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages

**Comment by toddkitchens** [comment]
Nav routing built and page component created.
